name: 'Deploy Python Greetings App'
description: 'Deploy Python Greetings application to specified environment'

inputs:
  env_name:
    description: 'Environment name (dev, staging, preprod, prod)'
    required: true
  port:
    description: 'Port number for the application'
    required: true

runs:
  using: "composite"
  steps:
    - name: Informational output
      shell: bash
      run: echo "Deploying to ${{ inputs.env_name }} environment..."
    
    - name: Checkout Python Greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
    
    - name: Stop service if exists (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.env_name }} & set "errorlevel=0"
    
    - name: Stop service if exists (Unix)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.env_name }} || true
    
    - name: Start application
      shell: bash
      working-directory: python-greetings
      run: |
        # Проверяем, что происходит с приложением
        echo "Current directory: $(pwd)"
        echo "Python version: $(python3 --version)"
        
        # Создаем виртуальное окружение, если его еще нет
        python3 -m venv venv || true
        
        # Активируем виртуальное окружение
        source venv/bin/activate
        
        # Устанавливаем зависимости в виртуальном окружении
        pip install -r requirements.txt
        
        # Проверяем установленные пакеты
        pip list
        
        # Запускаем приложение через pm2 с интерпретатором из виртуального окружения
        pm2 delete greetings-app-${{ inputs.env_name }} || true
        pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter $(pwd)/venv/bin/python -- --port ${{ inputs.port }}
        
        # Проверяем статус приложения
        pm2 status
        
        # Небольшая задержка для запуска приложения
        sleep 5